# Generated by Django 4.2 on 2023-04-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_theme_alter_template_footer_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
