# Generated by Django 4.2 on 2023-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_theme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='code',
            field=models.FileField(blank=True, null=True, upload_to='codes'),
        ),
    ]
