# Generated by Django 4.2.1 on 2023-06-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_code_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name_plural': 'Codes'},
        ),
    ]
