# Generated by Django 4.2.1 on 2023-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_code_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(default='default', max_length=75),
        ),
    ]
