# Generated by Django 3.2.4 on 2023-06-21 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='directories'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
