# Generated by Django 4.2.1 on 2023-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230621_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
